[project]
name = "250726-uv-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["pyproject/demo1", "pyproject/demo2"]

[tool.uv.sources]
demo1 = { workspace = true }
demo2 = { workspace = true }
