[project]
name = "250726-uv-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["pkg/pkg1", "pkg/pkg2", "pkg/pkg3"]

[tool.uv.sources]
pkg2 = { workspace = true }
