[project]
name = "demo2"
version = "0.1.0"
description = "Demo2 package that uses demo1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "demo1 @ git+https://github.com/lwmacct/250726-uv-study.git#subdirectory=pyproject/demo1",
]
